/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type storeEvent = ContractEventLog<{
  _content: string;
  0: string;
}>;

export interface RandomGen extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): RandomGen;
  clone(): RandomGen;
  methods: {
    getStoredItems(): NonPayableTransactionObject<string>;

    storeItems(_content: string): PayableTransactionObject<void>;
  };
  events: {
    storeEvent(cb?: Callback<storeEvent>): EventEmitter;
    storeEvent(options?: EventOptions, cb?: Callback<storeEvent>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "storeEvent", cb: Callback<storeEvent>): void;
  once(
    event: "storeEvent",
    options: EventOptions,
    cb: Callback<storeEvent>
  ): void;
}
